name: Say Hi! 👋
description: Say hi and save time
author: housten

input:
  who-to-greet:
    description: "Who should we say hi to"
    default: "class"
outputs:
  time:
    description: "the time we were friendly"

runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
