name: show env variables

on: 
  workflow_dispatch:
jobs:
  showmyvars:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [dev,qa]

    environment: ${{ matrix.env }}
    steps:
      - run: echo ${{vars.svcAccountName}} ; echo ${{ secrets.svcAccountPassword }}
      - if: matrix.env == "qa" 
        run: echo "QA Only"
      
       
        
